language: php
php:
    - hhvm
before_script:
 - |
    if [[ $TRAVIS_PHP_VERSION = "hhv"* ]]; then
      echo "hhvm.enable_hip_hop_syntax = true" >> /etc/hhvm/php.ini
    fi

script:
    - php --modules

