language: php
php:
    - 5.4
before_script:
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
    - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'> /tmp/10gen.list
    - sudo cp /tmp/10gen.list /etc/apt/sources.list.d/10gen.list
    - sudo apt-get update -qq
    - sudo apt-get install -qq memcached memcachedb mongodb-10gen
    - sudo pecl install memcache
    - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - pecl install mongo
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - pecl install gearman
    - echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

notifications:
  email:
    - necromant2005@gmail.com
